[package]
name = "recycle-tray-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.1"
tray-icon = "0.14.3"
winit = "0.30.3"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["shellapi"] }