name: create release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Compile and publish
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          zip: windows
          bin: recycle-tray-rs
